### ISSUE TITLE
Remove reference to Port 80 in your-own-containers.md

### ISSUE THREAD

**Issue by thatsnasty** [saltyorg/docs#11]
May I suggest removing reference to port 80 in the example format(s) for your-own-containers.md. I aware (now) that's its clearly referenced down the bottom of the page that it's the container port that should go here, but because it wasn't at least highlighted or maybe shown with a value of `<container_port>` I missed it when throwing a container together.

This is definitely a "just make sure you read the whole page" kinda thing but I thought it could relieve some headaches in the future for people half asleep like me.

**Comment by maximuskowalski** [comment]
Maybe a bold **APPPORT** to match the **APPNAME**?

**Comment by thatsnasty** [comment]
> 

Yep I agree

**Comment by maximuskowalski** [comment]
merged
