### ISSUE TITLE
Documentation Request: tdarr 

### ISSUE THREAD

**Issue by maximuskowalski** [saltyorg/docs#113]
Moving Docs Needed for tdarr issue from Sandbox repo to docs repo.

https://github.com/saltyorg/Sandbox/issues/22

**Comment by RaneyDazed** [comment]
I've never used it, does it require a login or anything?

**Comment by keldian** [comment]
Might need a word on tdarr-node and how to connect them the saltbox way.

**Comment by RaneyDazed** [comment]
I was thinking about doing that. But idk how it works, mind giving me a hand w that?

**Comment by RaneyDazed** [comment]
pr #123

**Comment by keldian** [comment]
I would, but I've never used nodes myself, I just noticed chatter suggesting it's a point of confusion.

**Comment by RaneyDazed** [comment]
> I would, but I've never used nodes myself, I just noticed chatter suggesting it's a point of confusion.

All good, I'll let someone that has used it take a look. I don't have a reason to use it atm.

**Comment by owine** [comment]
#124 for `tdarr_node`
