### ISSUE TITLE
Documentation Request: Audiobookshelf

### ISSUE THREAD

**Issue by ralleclub** [saltyorg/docs#115]
**Audiobookshelf** is a self-hosted audiobook server for managing and playing your audiobooks. Audiobookshelf has a clean, accessible design that's loaded with features but not overly complicated. Not only will it host your audiobooks, but Audiobookshelf will scan and host your Ebooks and podcasts. This also includes the iOS and Android apps that can be used in conjunction with the host side with playback sync. You can listen with the phone app on the go then continue where you left off on your laptop when you get home. Playback will seamlessly sync between all of your devices much like Plex or Jellyfin.

**Features and Support**
- Host and serve Audiobooks
- Host and serve Ebooks
- Host, search, automatically download and serve Podcasts
- Fully open-source, including the android & iOS app (in beta)
- Stream all audiobook formats on the fly
- Multi-user support w/ custom permissions
- Keeps progress per user and syncs across devices
- Auto-detects library updates, no need to re-scan
- Upload audiobooks w/ bulk upload drag and drop folders
- Backup your metadata + automated daily backups
- Progressive Web App (PWA)
- Chromecast support on the web app
- Fetch metadata and cover art from several sources

**Links**
- https://github.com/advplyr/audiobookshelf
- https://hub.docker.com/r/advplyr/audiobookshelf
- https://www.audiobookshelf.org/docs

**Comment by RaneyDazed** [comment]
pull #118
