### ISSUE TITLE
Documentation Request: Paperless NGX + with document store on google 

### ISSUE THREAD

**Issue by cstrand89** [saltyorg/docs#116]
A community-supported supercharged version of paperless: scan, index and archive all your physical documents. 

Example docker compose: https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.postgres-tika.yml

**Comment by RaneyDazed** [comment]
Pull #117

**Comment by maximuskowalski** [comment]
> @maximuskowalski Would you like the google bits included in docs?

In general, I am aiming to add the minimum amount of information needed to get the role installed and supply links to the official documentation if it exists. If there is other information or a short story that I want to include I might add a section after the more or less standard template ( I think you picked up on one of my Find Replace `APPNAME` mistakes :) ). Extra info and tips are great but not important. Usually if I am doing docs I have a bunch to do so I'm just trying to get _something_ in place.
