### ISSUE TITLE
Docs request: trackarr

### ISSUE THREAD

**Issue by TheUltimateC0der** [saltyorg/docs#164]
Tracker announcements to Sonarr/Radarr/Lidarr.

https://gitlab.com/cloudb0x/trackarr
https://hotio.dev/containers/trackarr/

**Comment by maximuskowalski** [comment]
> I guess it was because I couldnt find the docs for it.

Transferred issue to docs :) Thank you.

**Comment by RaneyDazed** [comment]
> > I guess it was because I couldnt find the docs for it.
> 
> Transferred issue to docs :) Thank you.

@maximuskowalski just curious, why is trackarr in saltbox? Is salty still taking care of the role? I'd assume there's not much going on w it. I'll try out making the docs after a bit.I'd set up trackarr a while back. although autobrr is better 🐇

**Comment by keldian** [comment]
Probably migrate https://gitlab.com/cloudb0x/trackarr/-/wikis or simply link to it.
Ask salty how he wants to play this out, since it's a saltbox role.

**Comment by saltydk** [comment]
Was l3uddz that originally added it to Cloudbox and I don't use the role personally so I'll happily move it to sandbox.

**Comment by owine** [comment]
> Was l3uddz that originally added it to Cloudbox and I don't use the role personally so I'll happily move it to sandbox.

Makes sense to me

**Comment by saltydk** [comment]
done
