### ISSUE TITLE
Argo Tunnel error

### ISSUE THREAD

**Issue by hacktronicsraj** [saltyorg/docs#214]
Getting Cloud Flare Argo Error while accessing login page of domain
![Screenshot 2023-07-09 at 7 12 49 PM](https://github.com/saltyorg/docs/assets/69853022/56ab994e-363f-42d3-be90-0c8f5bdc3dd5)

Please Help me out in resolving this error

**Comment by owine** [comment]
I don’t see the relevance to the project documentation
