### ISSUE TITLE
Issue with page rendering / possible search bug

### ISSUE THREAD

**Issue by nickheyer** [saltyorg/docs#216]
Just attempted to search for an addon using the search bar on the top right. It found the addon as expected, but the article's sub-header did not render correctly. See below screenshot.

![image](https://github.com/saltyorg/docs/assets/60236014/1bdf916b-6644-4cfb-9ea1-b3ce274f563a)

**Comment by saltydk** [comment]
fixed in https://github.com/saltyorg/docs/commit/c05124bded2112832ef9e5a5166ab78adfc1ac73
