### ISSUE TITLE
Plex - Not Authorized

### ISSUE THREAD

**Issue by roblange17** [saltyorg/docs#225]
I used the most basic as possible seedbox install parameters (no cloud mounting, etc.). I didn't get any errors during the install.

When I load https://plex.mydomain.com/web it gives me a "Not authorized You do not have access to this server." error. 

I've tried logging out and logging back in. It prompts to me authorize plex.domain.com, but after I login I see the same not authorized error. I do not have 2FA on.

Any idea what I'm missing?

**Comment by roblange17** [comment]
I'm able to run plex_auth_token and when I attempt to use it with /claim?token=XXX, I get a 401 error.

**Comment by saltydk** [comment]
Go to the discord for support, this isn't really the place.
