### ISSUE TITLE
Outdated instructions for Autoscan

### ISSUE THREAD

**Issue by PlexNation** [saltyorg/docs#250]
Hey 

Just a heads up to that the Autoscan instructions refer back Plex Autoscan in the migration instructions and https://docs.saltbox.dev/apps/plex-autoscan/#obtaining-the-plex-autoscan-url

**Comment by chazlarson** [comment]
That's the plex-autoscan page, so I'd expect that page to contain this information.  The migration instructions point to this page in the context of "if you are using plex_autoscan", which is correct in my view.  Can you point me to the autoscan instructions that refer to this link, as I can't find them?
