### ISSUE TITLE
Themepark no longer applies to docker containers

### ISSUE THREAD

**Issue by shreddeddonut** [saltyorg/docs#293]
New install on 22.04, inventory file is as follows. Ansible logs do not show any themepark lines to state it has downloaded the theme or applied. Docker containers do not have the style volume or env lines.

global_themepark_theme: "plex"
global_themepark_plugin_enabled: true

**Comment by owine** [comment]
All you’ve done is provision the plugin, you’ve not enabled any apps to use themepark. That is done individually and there is no global toggle
