### ISSUE TITLE
Plex Webtools default URL incorrect.

### ISSUE THREAD

**Issue by thatsnasty** [saltyorg/docs#3]
Wiki needs to be updated in accessing_apps.md to show the Plex Webtools address as `https://plex-webtools.yourdomain.com` and remove the * from the bottom.

**Comment by chazlarson** [comment]
Done.

![image](https://user-images.githubusercontent.com/3865541/137055735-88cc790d-f2a5-4a27-9e88-fb29218ed7df.png)
