### ISSUE TITLE
update to guide

### ISSUE THREAD

**Issue by Nunya-Biznus** [saltyorg/docs#300]
My vps had a minimal install of ubuntu and installing saltbox gave me errors.

I had to manually install pipx by doing

pip install pipx

Than I needed to install Ansible by doing

pipx install --include-deps ansible

Than the install scripts were able to run as normal if anyone else is having problems installing this.

**Comment by saltydk** [comment]
I'm currently debugging some changes to the script, this is not something people would ever have to do.

**Comment by saltydk** [comment]
Additionally it means your ansible install is incorrect, just so you're aware.

**Comment by saltydk** [comment]
The version of the install script I just pushed should have fixed the issue, I would recommend that you redo the install after the manual commands shown here.

**Comment by Nunya-Biznus** [comment]
Yes I did another install after the commands.  

This was done on a fresh install of ubuntu as well.

**Comment by saltydk** [comment]
Just run the script, on a clean install without your changes, with verbose enabled since the current problem is related to running without verbose enabled.

**Comment by saltydk** [comment]
Fixed without verbose now as well, at least in my own test.

**Comment by Nunya-Biznus** [comment]
its already done.  I was able to install everything after I ran the commands manually.

I would have to delete my setup and try again.  I am willing to try it, but will have to be another time.

Thanks for updating the script.

**Comment by saltydk** [comment]
Yeah, sorry about that, it was a weird sub shell issue that changed the exit code, setting it manually fixed it. I might look it over later to find out the exact cause but for now it works fine.

**Comment by Nunya-Biznus** [comment]
Hey,

just to let you know I redeployed a fresh install of ubuntu and updated and upgraded it to latest version.

Everything installed with no errors.  Thanks for the update.

Just one request for people who are not going to use rclone can there be an option to not even install it if we are not using it.

Thanks.

**Comment by chazlarson** [comment]
I thought disabling rclone in the settings skipped installing it.  Are you seeing something else?

![image](https://github.com/user-attachments/assets/f8011a33-b834-4c69-864f-20f1831841f4)

**Comment by Nunya-Biznus** [comment]
I edited the file and I put 

enabled: no

and this is from my vps

rclone version

rclone v1.67.0
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-117-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.4
- go/linking: static
- go/tags: none

**Comment by chazlarson** [comment]
Had you already gone through the setup with enabled: yes?

**Comment by Nunya-Biznus** [comment]
Nope. 

Brand new install of ubuntu and first time running this script.

**Comment by saltydk** [comment]
We will not have such a toggle since people that don't use the mount with
rcæone may still want to use it for the backup functionality.
