### ISSUE TITLE
Change trilium docker pull

### ISSUE THREAD

**Issue by mremptypants** [saltyorg/docs#301]
The old version is not being maintaned.  Please fix the sandbox role to 
# Image
trilium_docker_image_pull: true
trilium_docker_image_tag: "latest"
trilium_docker_image: "triliumnext/notes:{{ trilium_docker_image_tag }}"

I did a test rebuild and it works fine and will just move the old data.

**Comment by mremptypants** [comment]
also may need to fix these in the file.
./start-docker.sh: 3: [[: not found
./start-docker.sh: 4: [[: not found
No USER_UID specified, leaving 1000
No USER_GID specified, leaving 100

**Comment by owine** [comment]
https://github.com/saltyorg/Sandbox/commit/4852a8e9ba6ba448855ced8e7f6ad7f1fe23ab5d
