### ISSUE TITLE
Changing Advanced Settings After Install

### ISSUE THREAD

**Issue by lachiefish** [saltyorg/docs#96]
Hi there,
Not sure if I should be posting this here, but here I go anyway. Firstly, love your work and thank you;

Secondly, I just wanted to ask if it is possible to change the options in adv_settings.yml, specifically enabling nVidia GPU support, after installing and configuring the rest of saltbox; ie. I've had it installed for weeks now but I only just saw this option.

Thanks! :)
Lachie

**Comment by saltydk** [comment]
Should be enough to run ```sb install nvidia``` and then reinstall any roles that would use it, ie plex/emby/jellyfin.

**Comment by lachiefish** [comment]
Awesome, thank you!
